### ISSUE TITLE
Limited data displayed for high CPU count controllers

### ISSUE THREAD

**Issue by jkreienh** [ni/niveristand-system-monitor-custom-device#19]
**Controller:** PXIe-8881, 18 Core

**Issue:** No CPU data displayed for CPU16 and CPU17 as well as Memory Usage

![image](https://user-images.githubusercontent.com/34135562/149335978-04dd6131-5ab8-40f0-ba19-0a23679cf21f.png)

**Comment by buckd** [comment]
My best guess is this is a limitation of the implementation in `RT Get CPU Loads.vi` provided by LabVIEW Real-Time. If this VI works for only 16 CPUs, I would expect this output and, potentially, an error coming from that VI. That error would then be propagated to the calls for memory usage, which would return default data.

**Comment by jkreienh** [comment]
It looks like we get info correctly in MAX as well as htop.   I wasn't able to snag the htop values before it offloaded to a different CPU.

![image](https://user-images.githubusercontent.com/34135562/149356675-c90b45aa-edc2-46e2-b156-60bf7dca341f.png)

**Comment by jkreienh** [comment]
@buckd It looks like `RT Get CPU Loads.vi` works fine in LabVIEW Real-Time.

![image](https://user-images.githubusercontent.com/34135562/149358276-b8ede33b-cd62-4dc0-9acf-7d30bf11793c.png)

![image](https://user-images.githubusercontent.com/34135562/149358342-1d0f1037-7607-46a0-b818-9479169fa02a.png)

**Comment by buckd** [comment]
@jkreienh Both of those screenshots only show 16 CPUs.

**Comment by jkreienh** [comment]
@buckd I forgot how to count and looked at the last two CPUs for something other than zero usage.

FYI: Linux command htop only shows 16 as well!

![image](https://user-images.githubusercontent.com/34135562/149379467-84a8304c-be3a-436b-95a2-6b97294975b2.png)

**Comment by buckd** [comment]
So, now my guess is that VI is only returning 16 CPUs and then placing the memory stats next in the channel array, which is why you see crazy numbers for **Total** and **Time Critical** for CPU 16. If `RT Get CPU Loads.vi` and `htop` are both only returning 16 CPUs, nothing immediately comes to mind for a fix.

**Comment by jkreienh** [comment]
This issue seems to be fixed in LabView 2021.
